---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"

  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 15

    groups:
      pytest:
        patterns:
          - "pytest"
          - "pytest-*"

  - package-ecosystem: docker
    directory: "/backend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: "/frontend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
