---
name: Feature
description: Describe a feature that you want implemented.
title: "[FEATURE]: "
labels:
  - feature
body:
  - type: textarea
    id: problem-description
    validations:
      required: true
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem you are facing...

  - type: textarea
    id: solution-description
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution you want...

  - type: textarea
    id: alternative-solutions
    validations:
      required: false
    attributes:
      label: Describe alternatives you've considered
      description: Mention any alternative solutions or features you've considered.
      placeholder: Describe alternative solutions...

  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: Additional context
      description: Provide any extra context or screenshots related to the feature request.
      placeholder: Add any relevant context or details here...

  - type: checkboxes
    attributes:
      label: "Required"
      description: "Please confirm:"
      options:
        - label: "I have checked past issues to see if this feature has already been requested."
          required: true
